# 一維張量

In [1]:
import numpy as np

In [21]:
tensor_id = np.array([1.3, 1, 4.0, 23.99])

In [22]:
print tensor_id

[  1.3    1.     4.    23.99]


In [23]:
print tensor_id[0]

1.3


In [24]:
print tensor_id[3]

23.99


In [25]:
tensor_id.ndim

1

In [26]:
tensor_id.shape

(4,)

In [27]:
tensor_id.dtype

dtype('float64')

In [28]:
import tensorflow as tf

In [29]:
tf_tensor = tf.convert_to_tensor(tensor_id, dtype=tf.float64)

In [42]:
with tf.Session() as sess:
    print sess.run(tf_tensor)
    print sess.run(tf_tensor[0])
    print sess.run(tf_tensor[2])

[  1.3    1.     4.    23.99]
1.3
4.0


# 二維張量

In [43]:
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])

In [44]:
print tensor_2d

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [53]:
tensor_2d[3][2]

14

In [46]:
tensor_2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [52]:
tensor_2d[1:3,0:2]

array([[4, 5],
       [8, 9]])